server:
  ip: localhost
  port: "8080"
sqlite:
  dbfile: bluebell.db
logic:
  passwordrange:
    - 8
    - 20
  maxusernamelen:
    - 4
    - 16
  nduplicatelogin: 3
  maxpagesize: 10
redis:
  addr: localhost:6379
  password: ""
  tokendb: 0
  postdb: 1
  ratelimitdb: 2
  ttl_post_inorder_of_community: 20
ratelimit:
  rate: 20
  nbucket: 800
jwt:
  issuer: Bluebell
  expiretime: 2h0m0s
snowflake:
  starttime: "2020-01-01 00:00:00"
  datacenterid: 0
  machineid: 0
log:
  logfile: bluebell.log
  loglevel: info
